/**
 * load-test.js — k6 load test script
 *
 * Menguji 4 operasi CRUD pada endpoint /api/products.
 * Target API ditentukan via environment variable TARGET.
 *
 * Jalankan:
 *   docker compose --profile k6 run --rm k6 run /scripts/load-test.js \
 *     -e TARGET=http://springboot-api:8080 \
 *     --out csv=/results/sb-run-001.csv
 */

import http from "k6/http";
import { check, sleep } from "k6";
import { Rate } from "k6/metrics";

// ── Konfigurasi eksperimen (sesuai experiment-config) ─────────────────────────
export const options = {
  stages: [
    { duration: "30s", target: 20 },   // ramp-up
    { duration: "120s", target: 20 },  // steady-state (window pengukuran)
    { duration: "10s", target: 0 },    // ramp-down
  ],
  thresholds: {
    http_req_failed:   ["rate<0.05"],   // error rate < 5%
    http_req_duration: ["p(95)<2000"],  // p95 < 2000ms
  },
};

const BASE_URL = __ENV.TARGET || "http://localhost:8080";
const headers  = { "Content-Type": "application/json" };

// Custom metric
const errorRate = new Rate("error_rate");

// Pool ID dari dokumen yang sudah ada di DB — diisi saat setup
// dan dipakai oleh operasi GET by ID, UPDATE, DELETE
let existingIds = [];

// ── Setup: ambil beberapa ID dari DB sebelum test dimulai ────────────────────
export function setup() {
  const res = http.get(`${BASE_URL}/api/products?page=0&size=50`);
  if (res.status === 200) {
    try {
      const body = JSON.parse(res.body);
      if (Array.isArray(body)) {
        return { ids: body.map((p) => p.id).filter(Boolean) };
      }
    } catch (_) {}
  }
  return { ids: [] };
}

// ── Helper: ambil ID acak dari pool ──────────────────────────────────────────
function randomId(data) {
  if (!data || !data.ids || data.ids.length === 0) return null;
  return data.ids[Math.floor(Math.random() * data.ids.length)];
}

// ── Payload CREATE ────────────────────────────────────────────────────────────
function randomProduct() {
  const id = Math.floor(Math.random() * 9000000) + 1000000;
  return JSON.stringify({
    unique_id:            "BENCH-" + id,
    product_id:           String(id),
    product_name:         "Benchmark Product " + id,
    product_type:         "bench-item",
    product_measurements: "10x10x10 cm",
    product_description:  "Generated by k6 load test",
    main_category:        "benchmark",
    sub_category:         "load-test",
    product_rating:       4.0,
    product_rating_count: 1.0,
    badge:                "none",
    online_sellable:      "True",
    url:                  "https://example.com/p/" + id,
    price:                9.99,
    currency:             "USD",
    discount:             "none",
    sale_tag:             "NONE",
    country:              "TestLand",
  });
}

// ── Skenario utama: distribusi operasi CRUD ────────────────────────────────────
// GET paginated 50%, GET by ID 20%, POST 15%, PUT 10%, DELETE 5%
export default function (data) {
  const roll = Math.random();

  if (roll < 0.50) {
    // ── GET paginated (50%) ───────────────────────────────────────────────────
    const page = Math.floor(Math.random() * 100); // halaman 0-99
    const res  = http.get(`${BASE_URL}/api/products?page=${page}&size=20`);
    const ok   = check(res, { "GET 200": (r) => r.status === 200 });
    errorRate.add(!ok);

  } else if (roll < 0.70) {
    // ── GET by ID (20%) ───────────────────────────────────────────────────────
    const id = randomId(data);
    if (id) {
      const res = http.get(`${BASE_URL}/api/products/${id}`);
      const ok  = check(res, {
        "GET by ID 200": (r) => r.status === 200,
        "GET by ID 404": (r) => r.status === 404,
      });
      errorRate.add(res.status !== 200 && res.status !== 404);
    }

  } else if (roll < 0.85) {
    // ── CREATE (15%) ──────────────────────────────────────────────────────────
    const res = http.post(`${BASE_URL}/api/products`, randomProduct(), { headers });
    const ok  = check(res, { "POST 201": (r) => r.status === 201 });
    errorRate.add(!ok);

  } else if (roll < 0.95) {
    // ── UPDATE (10%) ──────────────────────────────────────────────────────────
    const id = randomId(data);
    if (id) {
      const res = http.put(
        `${BASE_URL}/api/products/${id}`,
        randomProduct(),
        { headers }
      );
      const ok = check(res, {
        "PUT 200": (r) => r.status === 200,
        "PUT 404": (r) => r.status === 404,
      });
      errorRate.add(res.status !== 200 && res.status !== 404);
    }

  } else {
    // ── DELETE (5%) ───────────────────────────────────────────────────────────
    const id = randomId(data);
    if (id) {
      const res = http.del(`${BASE_URL}/api/products/${id}`);
      const ok  = check(res, {
        "DEL 204": (r) => r.status === 204,
        "DEL 404": (r) => r.status === 404,
      });
      errorRate.add(res.status !== 204 && res.status !== 404);
    }
  }

  sleep(0.1);
}
